In [190]:
free_fest_lyrics = """
The children of the summer's end
Gathered in the dampened grass
We played Our songs and felt the London sky
Resting on our hands
It was God's land.
It was ragged and naive.
It was Heaven.

Touch, we touched the very soul
Of holding each and every life.
We claimed the very source of joy ran through.
It didn't, but it seemed that way.
I kissed a lot of people that day.

Oh, to capture just one drop of all the ecstasy 
that swept that afternoon,
To paint that love upon a white balloon,
And fly it from the toppest top 
of all the tops that man has 
pushed beyond his Brain.
Satoria must be something just the same.

We scanned the skies with rainbow eyes 
and saw machines of every shape and size.
We talked with tall Venusians passing through.
And Peter tried to climb aboard 
but the Captain shook his head
And away they soared,
Climbing through the ivory vibrant cloud.
Someone passed some bliss among the crowd.
And we walked back to the road, unchained.

The Sun Machine is coming down, 
and we're gonna have a party.
The Sun Machine is coming down, 
and we're gonna have a party.
The Sun Machine is coming down, 
and we're gonna have a party.
The Sun Machine is coming down, 
and we're gonna have a party.
The Sun Machine is coming down, 
and we're gonna have a party.
"""

In [191]:
lyric_list = [x for x in free_fest_lyrics.split("\n") if x]

### Create the vocab

In [192]:
def get_vocab(text):
    vocab = set()
    for line in text:
        vocab.update([word.lower() for word in line.split()])
    return(vocab)

vocab = get_vocab(lyric_list[0:2])
print(f'There are {len(vocab)} unique words in these lyrics:')
print(f'They are: {vocab}')

There are 9 unique words in these lyrics:
They are: {'children', 'in', 'of', 'grass', 'gathered', 'the', 'end', "summer's", 'dampened'}


### Set up the count vector

In [193]:
def vector_lookup(text):
    vocab_dict = {}
    vocab = get_vocab(text)
    for count, word in enumerate(vocab):
        vocab_dict[count] = word
    return(vocab_dict)

### Create an input vector

In [194]:
def input_vector(count_vector, input_text):
    input_count = {}
    input_vector = []
    # Get the count of words in the text
    for word in input_text.split():
        input_count[word.lower()] = input_count.get(word, 0)+1
    # Now create a vector based on our vocab
    vector_size = len(count_vector)
    for idx in range(vector_size):
        # Check if the input text exists in the vocab
        value = input_count.get(count_vector[idx], 0)
        input_vector.append(value)
    return(input_vector)

In [195]:
lyric_list[0:2]

["The children of the summer's end", 'Gathered in the dampened grass']

In [196]:
count_vector = vector_lookup(lyric_list[0:2])
print(count_vector)

{0: 'children', 1: 'in', 2: 'of', 3: 'grass', 4: 'gathered', 5: 'the', 6: 'end', 7: "summer's", 8: 'dampened'}


In [197]:
print(input_vector(count_vector, "The children played in the grass"))

[1, 1, 0, 1, 0, 2, 0, 0, 0]


### Use the full song lyrics

In [198]:
count_vector = vector_lookup(lyric_list)
full_vec = input_vector(count_vector, "The children played in the grass")
print(f'The new feture size is {len(count_vector)}')
print(full_vec)

The new feture size is 129
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


### A matrix of Bowie lyrics

In [214]:
import numpy as np
np.set_printoptions(threshold=10)
lyrics = []
for lyric in lyric_list[15:18]:
    print(lyric)
    vec = input_vector(count_vector, lyric)
    lyrics.append(vec)

# Turn the list into a multidimensional array or matrix
lyric_matrix = np.array(lyrics)
print(f'Matrix shape: {lyric_matrix.shape})')
print(lyric_matrix)

And fly it from the toppest top 
of all the tops that man has 
pushed beyond his Brain.
Matrix shape: (3, 129))
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
